// bento: CLI for invoking the bento sandbox.
//
//	bento doctor [--skip-network] [--fail-fast]
//	bento run [--timeout=DUR] [--env KEY=VALUE]... <manifest.yaml>
package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/whiskeyjimbo/bento"
	"github.com/whiskeyjimbo/bento/internal/grants"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	switch os.Args[1] {
	case "doctor":
		os.Exit(cmdDoctor(os.Args[2:]))
	case "run":
		os.Exit(cmdRun(os.Args[2:]))
	case "validate":
		os.Exit(cmdValidate(os.Args[2:]))
	case "init":
		os.Exit(cmdInit(os.Args[2:]))
	case "profile":
		os.Exit(cmdProfile(os.Args[2:]))
	case "-h", "--help", "help":
		usage()
		os.Exit(0)
	default:
		usage()
		os.Exit(2)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, "usage:")
	fmt.Fprintln(os.Stderr, "  bento doctor [--skip-network] [--fail-fast]")
	fmt.Fprintln(os.Stderr, "  bento run [--timeout=DUR] [--env KEY=VALUE]... [--network-mode=auto|landlock|bridge] <manifest.yaml | script.py>")
	fmt.Fprintln(os.Stderr, "    (script.py: zero-config practical-strict; auto interpreter via extension/shebang)")
	fmt.Fprintln(os.Stderr, "  bento validate <manifest.yaml>")
	fmt.Fprintln(os.Stderr, "  bento init [--dry-run]")
	fmt.Fprintln(os.Stderr, "  bento profile [--out=PATH] [--force] [--interpreter=BIN] <script.py>")
}

func cmdProfile(args []string) int {
	fs := flag.NewFlagSet("profile", flag.ExitOnError)
	out := fs.String("out", "", "manifest output path (default: <script>.manifest.yaml)")
	force := fs.Bool("force", false, "overwrite the output file if it already exists")
	interpreter := fs.String("interpreter", "", "override auto-detected interpreter")
	fs.Parse(args)
	if fs.NArg() != 1 {
		usage()
		return 2
	}
	scriptPath := fs.Arg(0)

	interp := *interpreter
	if interp == "" {
		var err error
		interp, err = bento.ResolveInterpreter(scriptPath)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			return 1
		}
	}
	m, err := bento.PracticalStrictManifest(scriptPath, interp)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}

	outPath := *out
	if outPath == "" {
		outPath = strings.TrimSuffix(scriptPath, filepath.Ext(scriptPath)) + ".manifest.yaml"
	}
	if !*force {
		if _, err := os.Stat(outPath); err == nil {
			fmt.Fprintf(os.Stderr, "error: %s already exists; --force to overwrite or --out=PATH\n", outPath)
			return 1
		}
	}

	fmt.Fprintf(os.Stderr, "[bento] profiling %q (permissive network)...\n", scriptPath)
	result, err := bento.Profile(context.Background(), m,
		bento.WithLogger(log.New(os.Stderr, "", log.LstdFlags)),
	)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}
	fmt.Fprintf(os.Stderr, "[bento] script exit code: %d\n\n", result.ExitCode)
	printObservations(os.Stderr, result.Observations)

	yamlBytes, err := yaml.Marshal(result.SuggestedManifest)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error marshaling suggested manifest:", err)
		return 1
	}
	header := "# generated by `bento profile " + scriptPath + "` — review and trim before use\n\n"
	if err := os.WriteFile(outPath, append([]byte(header), yamlBytes...), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "error writing manifest:", err)
		return 1
	}
	fmt.Fprintf(os.Stderr, "[bento] wrote %s — review and trim before running with `bento run`\n", outPath)
	return result.ExitCode
}

func printObservations(w io.Writer, obs []bento.NetworkObservation) {
	if len(obs) == 0 {
		fmt.Fprintln(w, "[bento] no network observations")
		return
	}
	fmt.Fprintln(w, "[bento] observed network:")
	fmt.Fprintf(w, "  %-32s  %-6s  %s\n", "Host", "Port", "Count")
	fmt.Fprintf(w, "  %-32s  %-6s  %s\n", "----", "----", "-----")
	for _, o := range obs {
		fmt.Fprintf(w, "  %-32s  %-6d  %d\n", o.Host, o.Port, o.Count)
	}
	fmt.Fprintln(w)
}

func cmdInit(args []string) int {
	fs := flag.NewFlagSet("init", flag.ExitOnError)
	dryRun := fs.Bool("dry-run", false, "print plan without making changes")
	fs.Parse(args)
	var opts []bento.InitOption
	if *dryRun {
		opts = append(opts, bento.WithDryRun())
	}
	_, err := bento.Init(context.Background(), os.Stdout, opts...)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}
	return 0
}

func cmdValidate(args []string) int {
	if len(args) != 1 {
		usage()
		return 2
	}
	f, err := os.Open(args[0])
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}
	defer f.Close()
	if _, err := bento.LoadManifest(f); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}
	fmt.Println("ok")
	return 0
}

func cmdDoctor(args []string) int {
	fs := flag.NewFlagSet("doctor", flag.ExitOnError)
	skipNetwork := fs.Bool("skip-network", false, "omit network-dependent checks (faster CI)")
	failFast := fs.Bool("fail-fast", false, "stop at the first FAIL")
	fs.Parse(args)

	var opts []bento.CheckOption
	if *skipNetwork {
		opts = append(opts, bento.WithSkipNetwork())
	}
	if *failFast {
		opts = append(opts, bento.WithFailFast())
	}
	if bento.Doctor(os.Stdout, opts...) {
		return 0
	}
	return 1
}

// envFlag collects repeated --env KEY=VALUE pairs.
type envFlag map[string]string

func (e envFlag) String() string {
	var parts []string
	for k, v := range e {
		parts = append(parts, k+"="+v)
	}
	return strings.Join(parts, ",")
}

func (e envFlag) Set(s string) error {
	k, v, ok := strings.Cut(s, "=")
	if !ok {
		return fmt.Errorf("expected KEY=VALUE, got %q", s)
	}
	e[k] = v
	return nil
}

func cmdRun(args []string) int {
	fs := flag.NewFlagSet("run", flag.ExitOnError)
	timeout := fs.Duration("timeout", 0, "wall-clock timeout (e.g. 30s, 5m). 0 = no timeout.")
	env := envFlag{}
	fs.Var(env, "env", "extra env var KEY=VALUE for the sandboxed script (repeatable)")
	netMode := fs.String("network-mode", "auto", "auto|landlock|bridge — Linux network strategy")
	telemetryOut := fs.String("telemetry-out", "", "capture script's fd 3 writes to this file path; '-' for stdout")
	interpreter := fs.String("interpreter", "", "override auto-detected interpreter (zero-config mode only)")
	prompt := fs.Bool("prompt", false, "interactively prompt via /dev/tty on allowlist misses (per-Run cached)")
	fs.BoolVar(prompt, "i", false, "shorthand for --prompt")
	fs.Parse(args)

	if fs.NArg() != 1 {
		usage()
		return 2
	}
	mode, ok := bento.ParseNetworkMode(*netMode)
	if !ok {
		fmt.Fprintf(os.Stderr, "error: unknown --network-mode %q (want auto|landlock|bridge)\n", *netMode)
		return 2
	}
	var telemetry io.Writer
	if *telemetryOut == "-" {
		telemetry = os.Stdout
	} else if *telemetryOut != "" {
		f, err := os.Create(*telemetryOut)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error opening --telemetry-out:", err)
			return 1
		}
		defer f.Close()
		telemetry = f
	}
	var grantCB bento.GrantCallback
	if *prompt {
		cb, err := grants.TTYCallback()
		if err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			return 1
		}
		grantCB = cb
	}

	target := fs.Arg(0)
	if isManifestPath(target) {
		return runManifest(target, *timeout, env, mode, telemetry, grantCB)
	}
	return runScriptZeroConfig(target, *interpreter, *timeout, env, mode, telemetry, grantCB)
}

// isManifestPath returns true if the path looks like a YAML manifest
// (vs. a script). We dispatch on extension; .yaml / .yml are manifest
// mode, everything else gets zero-config script handling.
func isManifestPath(p string) bool {
	ext := strings.ToLower(filepath.Ext(p))
	return ext == ".yaml" || ext == ".yml"
}

// runScriptZeroConfig synthesizes a practical-strict manifest for the
// given script and runs it. Interpreter is auto-detected unless
// overridden.
func runScriptZeroConfig(scriptPath, interpOverride string, timeout time.Duration, env map[string]string, netMode bento.NetworkMode, telemetry io.Writer, grantCB bento.GrantCallback) int {
	interp := interpOverride
	if interp == "" {
		var err error
		interp, err = bento.ResolveInterpreter(scriptPath)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			return 1
		}
	}
	m, err := bento.PracticalStrictManifest(scriptPath, interp)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}
	opts := []bento.Option{
		bento.WithLogger(log.New(os.Stderr, "", log.LstdFlags)),
		bento.WithNetworkMode(netMode),
	}
	if timeout > 0 {
		opts = append(opts, bento.WithTimeout(timeout))
	}
	if len(env) > 0 {
		opts = append(opts, bento.WithExtraEnv(env))
	}
	if telemetry != nil {
		opts = append(opts, bento.WithTelemetry(telemetry))
	}
	if grantCB != nil {
		opts = append(opts, bento.WithGrantCallback(grantCB))
	}
	code, err := bento.Run(context.Background(), m, opts...)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}
	return code
}

func runManifest(manifestPath string, timeout time.Duration, env map[string]string, netMode bento.NetworkMode, telemetry io.Writer, grantCB bento.GrantCallback) int {
	abs, err := filepath.Abs(manifestPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}
	f, err := os.Open(abs)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}
	m, err := bento.LoadManifest(f)
	f.Close()
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}
	if !filepath.IsAbs(m.Script) {
		m.Script = filepath.Join(filepath.Dir(abs), m.Script)
	}

	opts := []bento.Option{
		bento.WithLogger(log.New(os.Stderr, "", log.LstdFlags)),
	}
	if timeout > 0 {
		opts = append(opts, bento.WithTimeout(timeout))
	}
	if len(env) > 0 {
		opts = append(opts, bento.WithExtraEnv(env))
	}
	opts = append(opts, bento.WithNetworkMode(netMode))
	if telemetry != nil {
		opts = append(opts, bento.WithTelemetry(telemetry))
	}
	if grantCB != nil {
		opts = append(opts, bento.WithGrantCallback(grantCB))
	}

	code, err := bento.Run(context.Background(), m, opts...)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}
	return code
}
